"""
Centralized path configuration for the Folic Acid MEA / HIPPIE analysis.

All scripts import paths from here instead of hard-coding them.
To run on a different machine, either:
  1. Edit the defaults below, OR
  2. Set environment variables (see comments)
"""

from pathlib import Path
import os

# ── Project root (this file's directory) ──────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent

# ── Raw data ──────────────────────────────────────────────────────────────
# Kilosort spike-sorted outputs organized by date/mouse/run/well
DATA_RAW    = PROJECT_ROOT / "data" / "raw"
DATA_RAW_T3 = PROJECT_ROOT / "data" / "FolicAcid_T3_10222024_PS_PhyExport" / \
              "FolicAcid_T3_10222024_PS_PhyExport" / \
              "FolicAcid_T3_10222024_PS_PhyExport"
#DATA_RAW    = PROJECT_ROOT / "data" / "raw"       # T4 (original + remaining)
#DATA_RAW_T3 = PROJECT_ROOT / "data" / "raw_t3"    # T3 experiment

# ── Preprocessed data ─────────────────────────────────────────────────────
# Per-well CSVs (waveforms, ISI, ACG, metadata) generated by 00_preprocess.py
DATA_PROCESSED    = PROJECT_ROOT / "data" / "processed"
DATA_PROCESSED_T3 = PROJECT_ROOT / "data" / "processed_t3"

# ── HIPPIE input directories ─────────────────────────────────────────────
# Combined CSV files for HIPPIE training (waveforms.csv, isi_dist.csv, acg.csv,
# metadata.csv, labels.csv — one row per QC-passing unit across all wells)

# T4 dataset
HIPPIE_INPUT = Path(os.environ.get(
    "HIPPIE_INPUT_DIR",
    "/home/jesus/datasets_hippie/FA_T4"
))

# T3 dataset
HIPPIE_INPUT_T3 = Path(os.environ.get(
    "HIPPIE_INPUT_T3_DIR",
    str(PROJECT_ROOT / "data" / "hippie_input_t3")
))
#HIPPIE_INPUT_T3 = Path(os.environ.get(
#    "HIPPIE_INPUT_T3_DIR",
#    "/home/jesus/datasets_hippie/FA_T3"
#))

# Key files inside HIPPIE_INPUT (T4)
METADATA_CSV  = HIPPIE_INPUT / "metadata.csv"
LABELS_CSV    = HIPPIE_INPUT / "labels.csv"
WAVEFORMS_CSV = HIPPIE_INPUT / "waveforms.csv"
ACG_CSV       = HIPPIE_INPUT / "acg.csv"
ISI_CSV       = HIPPIE_INPUT / "isi_dist.csv"

# Key files inside HIPPIE_INPUT_T3
METADATA_CSV_T3  = HIPPIE_INPUT_T3 / "metadata.csv"
LABELS_CSV_T3    = HIPPIE_INPUT_T3 / "labels.csv"
WAVEFORMS_CSV_T3 = HIPPIE_INPUT_T3 / "waveforms.csv"
ACG_CSV_T3       = HIPPIE_INPUT_T3 / "acg.csv"
ISI_CSV_T3       = HIPPIE_INPUT_T3 / "isi_dist.csv"

# ── HIPPIE code & environment ─────────────────────────────────────────────
# Override: export HIPPIE_CODE_DIR=/your/path
HIPPIE_CODE = Path(os.environ.get(
    "HIPPIE_CODE_DIR",
    "/home/jesus/hippie_rebuttals/hip-hip-hippie"
))
HIPPIE_VENV_PYTHON = HIPPIE_CODE / "hippie_venv" / "bin" / "python"

# ── HIPPIE results ────────────────────────────────────────────────────────
# Where HIPPIE writes embeddings and checkpoints after training
HIPPIE_RESULTS = Path(os.environ.get(
    "HIPPIE_RESULTS_DIR",
    "/home/jesus/hippie_rebuttals/results_hippie_rebuttals/FA_T4"
))
HIPPIE_RESULTS_T3 = Path(os.environ.get(
    "HIPPIE_RESULTS_T3_DIR",
    "/home/jesus/hippie_rebuttals/results_hippie_rebuttals/FA_T3"
))

# ── Analysis results (outputs of scripts 01–09) ──────────────────────────
RESULTS_ROOT    = PROJECT_ROOT / "results"
RESULTS_EDA     = RESULTS_ROOT / "eda"
RESULTS_EMB     = RESULTS_ROOT / "embeddings"
RESULTS_NETWORK = RESULTS_ROOT / "network"
RESULTS_COND    = RESULTS_ROOT / "condition_eda"
RESULTS_FIGURES = RESULTS_ROOT / "figures"


# ── Helper functions ──────────────────────────────────────────────────────

def embedding_dir(config="full_model", z_dim=32, beta=4.0, run_suffix=""):
    """Return the HIPPIE results subdirectory for a given training config."""
    return HIPPIE_RESULTS_T3 / f"config_{config}_zdim_{z_dim}_B_{beta}{run_suffix}"


def embedding_file(epochs, config="full_model", z_dim=32, beta=4.0, run_suffix=""):
    """Return path to parsed embedding CSV for a specific epoch count."""
    d = embedding_dir(config, z_dim, beta, run_suffix)
    ep_file = d / f"embeddings_parsed_ep{epochs}.csv"
    if ep_file.exists():
        return ep_file
    generic = d / "embeddings_parsed.csv"
    if generic.exists():
        return generic
    return d / "pretraining_multi_embeddings.csv"  # raw fallback


def results_embedding_dir(epochs, run_suffix="", resid_tag=""):
    """Return output directory for embedding analysis results."""
    tag = f"epochs_{epochs}{run_suffix}{resid_tag}"
    return RESULTS_EMB / tag


def results_hdbscan_dir(epochs):
    """Return output directory for HDBSCAN clustering results."""
    return RESULTS_EMB / f"epochs_{epochs}_hdbscan"
